openapi: 3.0.0
info:
  title: Game Data API
  version: 1.0.0
paths:
  /api/store_game:
    post:
      summary: Store game data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                JUNGLE:
                  type: array
                  items:
                    $ref: '#/components/schemas/Player'
                BOTTOM:
                  type: array
                  items:
                    $ref: '#/components/schemas/Player'
                UTILITY:
                  type: array
                  items:
                    $ref: '#/components/schemas/Player'
                TOP:
                  type: array
                  items:
                    $ref: '#/components/schemas/Player'
                MIDDLE:
                  type: array
                  items:
                    $ref: '#/components/schemas/Player'
      responses:
        200:
          description: Game data stored successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Player:
      type: array
      items:
        type: string
